### ISSUE TITLE
Display de control

### ISSUE THREAD

**Issue by JohanelSteve** [JohanelSteve/Introduccion-en-HDL#3]
El display de control será prácticamente la salida de nuestro sistema de trabajo, la idea de esta etapa es visualizar de manera correcta los resultados de los modos de operación, el display de control no es la unica manera de revisar el funcionamiento del trabajo, puesto además a cada etapa será necesario realizarle test Beth para ver si correcto funcionamiento. 

La etapa de salida del display de control (display de 7 segmentos) será realizada solo por una persona y dicha persona se encargar solamente de esta sección, puesto se considera una etapa medianamente complicada.

La persona a cargo es: Fabrizio Vivas

**Comment by Fzi0** [comment]
Se tuvo un problema con la interpretación de la entrada y el funcionamiento del display 7 segmentos: entra la duda estaba como se recibian los bits de entrada y como se podria implementar.
